
package gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.WindowConstants;

/**
 *
 * @author Luis Miguel
 */
public class AppFavoritos extends javax.swing.JFrame {

    /**
     * Creates new form AppPerro
     */
    public AppFavoritos() {
        initComponents();
        
        setSize(890,590);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        //change imagen
        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo.png");
        
        //adapt to jlabel
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),jLabel_wallpaper.getHeight(),Image.SCALE_DEFAULT));
        
        //add to jlabel
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/"));
        return retValue;
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelTitulo = new javax.swing.JLabel();
        txtImgPerrito = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnFavorito = new javax.swing.JButton();
        jlabelInfo = new javax.swing.JLabel();
        jlabelTituloPerrito = new javax.swing.JLabel();
        txtPrincipal = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnLogo = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();
        btnFavoritos = new javax.swing.JButton();
        btnInicio1 = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameAppPrincipal"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelTitulo.setText("Mira a tus perritos favoritos");
        getContentPane().add(jlabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        txtImgPerrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImgPerritoActionPerformed(evt);
            }
        });
        getContentPane().add(txtImgPerrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 350, 240));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 50, 50));

        btnFavorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente.png"))); // NOI18N
        getContentPane().add(btnFavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 50, 50));

        jlabelInfo.setText("info......");
        getContentPane().add(jlabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 150, 50));

        jlabelTituloPerrito.setText("Ama a tu peludo!");
        getContentPane().add(jlabelTituloPerrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        txtPrincipal.setPreferredSize(new java.awt.Dimension(770, 580));
        txtPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 610, 540));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("  Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 180, 40));

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-perroapp.png"))); // NOI18N
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 90));

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        btnPerfil.setText(" Perfil");
        getContentPane().add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 40));

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ajustes.png"))); // NOI18N
        btnAjustes.setText(" Ajustes");
        getContentPane().add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 40));

        btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favorito.png"))); // NOI18N
        btnFavoritos.setText(" Favoritos");
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });
        getContentPane().add(btnFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 40));

        btnInicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        btnInicio1.setText(" Inicio");
        btnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrincipalActionPerformed

    private void txtImgPerritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImgPerritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgPerritoActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicio1ActionPerformed

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    public Icon setIcono(String url, JButton boton){
       ImageIcon icon = new  ImageIcon(getClass().getResource(url));
       
       int w = boton.getWidth();
       int h = boton.getHeight();
       
       ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(w,h,Image.SCALE_DEFAULT));
       return icono;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFavoritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFavorito;
    private javax.swing.JButton btnFavoritos;
    private javax.swing.JButton btnInicio1;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JLabel jlabelInfo;
    private javax.swing.JLabel jlabelTitulo;
    private javax.swing.JLabel jlabelTituloPerrito;
    private javax.swing.JTextField txtImgPerrito;
    private javax.swing.JTextField txtPrincipal;
    // End of variables declaration//GEN-END:variables
}
